# Generated by Django 3.0.4 on 2020-03-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('patient_capacity', models.PositiveIntegerField()),
                ('wait_time', models.DurationField()),
                ('drive_time', models.DurationField()),
            ],
        ),
    ]
