# Generated by Django 3.0.4 on 2020-03-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='drive_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='wait_time',
            field=models.PositiveIntegerField(),
        ),
    ]
